# Exercise: Complete this Dockerfile for a .NET 8 console app
# that prints "Hello from Docker!" and exits.

# TODO: Choose the correct SDK base image for building
FROM ??? AS build
WORKDIR /src

# TODO: Copy the .csproj and restore
# TODO: Copy the source and publish

# TODO: Choose the correct runtime base image (smaller than SDK)
FROM ??? AS runtime
WORKDIR /app

# TODO: Copy the published output from the build stage
# TODO: Set the ENTRYPOINT
