# Exercise: Complete this Dockerfile for a Python script that prints
# "Hello from Docker!" and the current Python version.

# TODO: Choose the correct slim base image for Python 3.12
FROM ???

WORKDIR /app

# TODO: Copy the script into the image
# TODO: Run it with CMD
