version: '3.9'
services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: testaccounts
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1234"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: testaccounts
      DB_USER: postgres
      DB_PASSWORD: "1234"
      FRONTEND_DIR: ./frontend
    depends_on:
      - postgres

volumes:
  pgdata:
